# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='thingspeak id')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('elevation', models.CharField(max_length=128, verbose_name='elevation')),
                ('last_entry_id', models.IntegerField(verbose_name='Last entry id')),
                ('ranking', models.IntegerField(verbose_name='Ranking')),
            ],
        ),
    ]
