# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20170126_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Api \u043a\u043b\u044e\u0447 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430 \u043d\u0430 thingspeak.com', max_length=128, verbose_name='API key')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
