# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='api_key',
            field=models.CharField(help_text='Api KEY \u043d\u0430 thingspeak.com (\u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e: 3BLVIV5M1A3COYBF)', max_length=128, verbose_name='API key'),
        ),
    ]
